// NEVAHEX-VM — optional dynamic-load path (spec Phase 2 sanctioned exception)
//
// "If dynamic code generation is absolutely necessary … it must use
//  string.dump + load on self-generated bytecode that is itself encrypted —
//  and this path must be optional, disabled for Luau."
//
// NV_DYNLOAD materializes a fresh native closure for a source-level Lua
// function via string.dump + load when the host allows it; otherwise the
// function is returned unchanged (pure interpreter fallback). The dump bytes
// are XOR-masked with a rolling key so the plaintext Lua bytecode never rests
// unencrypted in memory-visible constants.

export interface DynLoadNames {
  fn: string; // generated name of the helper local
}

export interface DynLoadEmit {
  lines: string[];
  /** name to reference from protected code (the helper) */
  ref: string;
}

/**
 * Emit the opt-in prelude. Returns null when disabled or when the target
 * cannot support it (Luau has no string.dump / load).
 */
export function emitDynLoadPrelude(
  enabled: boolean,
  envProfile: "lua51" | "luajit" | "luau" | "universal",
  names: DynLoadNames,
): DynLoadEmit | null {
  if (!enabled || envProfile === "luau") return null;

  const lines = [
    `local ${names.fn}`,
    `do`,
    `  local dump, load = string.dump, load`,
    `  if dump and load then`,
    `    function ${names.fn}(f, mask)`,
    `      local ok, d = pcall(dump, f)`,
    `      if not ok or type(d) ~= "string" then return f end`,
    `      local out = {}`,
    `      local g = (mask or 1) % 2147483646`,
    `      if g == 0 then g = 1 end`,
    `      for i = 1, #d do`,
    `        g = (g * 48271) % 2147483647`,
    `        out[i] = (string.byte(d, i) + g % 256) % 256`,
    `      end`,
    // masked blob rests encrypted; only re-materialized on demand
    `      return function(...)`,
    `        local gg = (mask or 1) % 2147483646`,
    `        if gg == 0 then gg = 1 end`,
    `        local parts = {}`,
    `        for i = 1, #out do`,
    `          gg = (gg * 48271) % 2147483647`,
    `          parts[i] = string.char((out[i] - gg % 256 + 256) % 256)`,
    `        end`,
    `        local f2 = load(table.concat(parts))`,
    `        if not f2 then return f end`,
    `        return f2(...)`,
    `      end`,
    `    end`,
    `  else`,
    `    function ${names.fn}(f) return f end`,
    `  end`,
    `end`,
  ];
  return { lines, ref: names.fn };
}
